# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 616c7da7b6b57bc7fb2e0b4293aa6bbe7bdc4b6f0124c547e814524f70d05d1b99dd4e9ad6ff093546b517800fd9cb6fb1eb284b6ec8332b4a1148908b4e395f

test:
  secret_key_base: c41d344b069b708bd5170ecaedb22882622b0fea7a84824e512e51576969d255762238f6a33dbd8d75c676f1294f9d39823071083e1c46f49b887fec6bb81588

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
